# Generated by Django 5.0.4 on 2024-04-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productt',
            old_name='quantity',
            new_name='category',
        ),
        migrations.AddField(
            model_name='productt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='productt',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
