# Generated by Django 5.0.4 on 2024-04-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_quantity_productt_category_productt_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_phone', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
