# Generated by Django 5.0.4 on 2024-04-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_cartitem_product_alter_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productt',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
