# Generated by Django 5.0.3 on 2024-05-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_userr_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
